version: '3.8'
services:
  app:
    image: open-chat-server:V1
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/database
      GEMINI_API_KEY: xxxxxxxxxxxxxxxxxxxxxxx
      AZURE_SPEECH_API_KEY: xxxxxxxxxxxxxxxxxxxxxxx
      TWILIO_AUTH_TOKEN: xxxxxxxxxxxxxxxxxxxxxxx
      TWILIO_ACCOUNT_SID: xxxxxxxxxxxxxxxxxxxxxxx
      TWILIO_VERIFY_SID: xxxxxxxxxxxxxxxxxxxxxxx
      REACTJS_BUILD_FOLDER: ./build
      OPENAI_API_KEY: xxxxxxxxxxxxxxxxxxxxxxx
    depends_on:
      - db_migration

  db_migration:
    image: open-chat-server:V1
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/database
    command: sh -c "prisma migrate deploy"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
